### ISSUE TITLE
Incomplete setup documentation

### ISSUE THREAD

**Issue by kallisti5** [looorent/keycloak-admin-ruby#12]
The keycloak setup documentation is pretty scarce around client setup:

* Which Client Protocol?  Seems like openid-connect and not saml?
* root url?
* base url?
* url vs domain? 

The terminology doesn't seem consistent between the ruby gem and keycloak.

**Comment by kallisti5** [comment]
As an example, with some guesses based on the documentation, I got here:
```

KeycloakAdmin.configure do |config|
  config.use_service_account = false
  config.server_url          = "https://auth.haiku-os.org/auth"
  config.server_domain       = "auth.haiku-os.org"
  config.client_id           = "admin-ruby"
  config.client_realm_name   = "haiku"
  config.use_service_account = false
  config.username            = "XXX"
  config.password            = "XXX"
  config.logger              = Logger.new(STDOUT)
  config.rest_client_options = { verify_ssl: OpenSSL::SSL::VERIFY_NONE }
end
```

A lot if it is just guesses though.

**Comment by looorent** [comment]
Hi @kallisti5 , thanks for your feedback.
You are right, the original documentation was based on Keycloak... 2.5 :)
I have modified the documentation accordingly.
