### ISSUE TITLE
What about sub groups?

### ISSUE THREAD

**Issue by chbach** [looorent/keycloak-admin-ruby#16]
I just checked out the gem and found out that the group representation is missing the subGroups. Are there any plans to implement that?

**Comment by looorent** [comment]
Hello @chbach . I do not plan to implement it, but I would be pleased to review a PR and integrate it.

**Comment by looorent** [comment]
Implemented by https://github.com/looorent/keycloak-admin-ruby/pull/22 in version `1.0.20`
